# Penguin's eggs
# krill.yaml
---
# welcome (put your language, example: it_IT.UTF-8)
language: 'es_SP.UTF-8'

# location (put your location, example region: "Europe", zone: "Rome")
region: 'Europe'
zone: 'Madrid'

# keyboard (put your values example: keyboardModel: "pc105", keyboardLayout: "it")
keyboardModel: 'pc105'
keyboardLayout: 'es'
keyboardVariant: ''
keyboardOption: ''

# partition (leave it unchanged)
installationDevice: ''
installationMode: 'standard'
filesystemType: 'ext4'
userSwapChoice: 'small'

# users (Here you can put your default user, password, etc)
name: 'zanthus'
fullname: 'zanthus'
password: 'zanthus'
rootPassword: 'zanthus'
autologin: true
hostname: ''

# network (leave it unchanged)
iface: ""
addressType: 'dhcp'
address: ''
netmask: ''
gateway: ''
domain: ''
dns: ''
